# Use an official Python runtime as a parent image
FROM python:3.9

# Install Docker CLI in the container
RUN apt-get update \
    && apt-get install -y sudo \
    && sudo apt install default-jdk -y

# Set the working directory in the container
WORKDIR /workspace/BaningAnalysis

# Copy the current directory contents into the container at /workspace
COPY . /workspace/BaningAnalysis

# pip dependence
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools


